# Generated by Django 3.1.2 on 2022-05-28 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeliculaProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('codigo', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(null=True, upload_to='peliculas')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.pelicula')),
            ],
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
