# Generated by Django 3.1.2 on 2022-05-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220528_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculaproducto',
            name='urlpelicula',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
