# Generated by Django 3.1.2 on 2022-05-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_peliculaproducto_urlpelicula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculaproducto',
            name='urlpelicula',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
