# Generated by Django 3.1.2 on 2022-05-29 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220529_0219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='nombre',
            new_name='nombrecontacto',
        ),
    ]
