# Generated by Django 4.0.4 on 2022-06-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_contacto_id_alter_pelicula_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculaproducto',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
