# Generated by Django 4.0.4 on 2022-06-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_contacto_id_alter_pelicula_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='nombrecontacto',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='contacto',
            name='tipo_consulta',
            field=models.IntegerField(choices=[[0, 'Consultas'], [1, 'Sugerencias'], [2, 'Recuperacion'], [3, 'Agradecimientos']]),
        ),
    ]
