# Generated by Django 4.0.4 on 2022-06-02 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_peliculaproducto_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='nombrecontacto',
            new_name='nombre',
        ),
    ]
